<?php
/**
 * This code was generated by
 *  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
 * | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
 * |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
 * |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reach\Rest;

use Reach\Domain;
use Reach\Exceptions\ReachException;
use Reach\Rest\Api\Messaging;
use Reach\Rest\Api\Authentix;

/**
 * @property \Reach\Rest\Api\Messaging $messaging
 * @property \Reach\Rest\Api\Authentix $authentix
 */
class ApiBase extends Domain {
    protected $_messaging;
    protected $_authentix;

    /**
     * Construct the Api Domain
     *
     * @param Client $client Client to communicate with Reach
     */
    public function __construct(Client $client) {
        parent::__construct($client);

        $this->baseUrl = 'https://api.reach.talkylabs.com';
    }


    /**
     * @return Messaging api
     */
    protected function getMessaging(): Messaging {
        if (!$this->_messaging) {
            $this->_messaging = new Messaging($this);
        }
        return $this->_messaging;
    }


    /**
     * @return Authentix api
     */
    protected function getAuthentix(): Authentix {
        if (!$this->_authentix) {
            $this->_authentix = new Authentix($this);
        }
        return $this->_authentix;
    }

    /**
     * Magic getter to lazy load version
     *
     * @param string $name Version to return
     * @return \Reach\Version The requested version
     * @throws ReachException For unknown versions
     */
    public function __get(string $name) {
        $method = 'get' . \ucfirst($name);
        if (\method_exists($this, $method)) {
            return $this->$method();
        }

        throw new ReachException('Unknown version ' . $name);
    }

    /**
     * Magic caller to get resource contexts
     *
     * @param string $name Resource to return
     * @param array $arguments Context parameters
     * @return \Reach\InstanceContext The requested resource context
     * @throws ReachException For unknown resource
     */
    public function __call(string $name, array $arguments) {
        $method = 'context' . \ucfirst($name);
        if (\method_exists($this, $method)) {
            return \call_user_func_array([$this, $method], $arguments);
        }

        throw new ReachException('Unknown context ' . $name);
    }

    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string {
        return '[Reach.Api]';
    }
}
