<?php
/**
 * This code was generated by
 *  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
 * | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
 * |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
 * |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reach\Rest;

use Reach\Base\BaseClient as BaseClient;
use Reach\Rest\Api\Messaging;
use Reach\Rest\Api\Authentix;


/**
 * A client for accessing the Reach API.
 * 
 * @property Messaging $messaging
 * @property Authentix $authentix
 * @property Api $api
 */

class Client extends BaseClient {
    protected $_api;

    /**
     * Access the Api Reach Domain
     *
     * @return Api Api Reach Domain
     */
    protected function getApi(): Api {
        if (!$this->_api) {
            $this->_api = new Api($this);
        }
        return $this->_api;
    }
    /**
     * Access the Messaging Reach Domain
     *
     * @return Messaging Messaging Reach Domain
     */
    protected function getMessaging(): Messaging {
        return $this->api->messaging;
    }
    /**
     * Access the Authentix Reach Domain
     *
     * @return Authentix Authentix Reach Domain
     */
    protected function getAuthentix(): Authentix {
        return $this->api->authentix;
    }
}
